# 钦念 调整于 2019.11.23
# 配置菜单导航的名称、路径和图标icon.
menu:
  Index:
    url: /
    icon: fa-home
  Tags:
    url: /tags
    icon: fa-tags
  Categories:
    url: /categories
    icon: fa-bookmark
  Archives:
    url: /archives
    icon: fa-archive
  About:
    url: /about
    icon: fa-user-circle-o
  Contact:
    url: /contact
    icon: fa-comments
  Friends:
    url: /friends
    icon: fa-address-book

# 站点运行开始时间.
time: 10/12/2019 00:00:00         # 格式为:月/日/年 时:分:秒. 

# 首页封面轮播图
cover:
  showPrevNext: true              #  是否显示左右切换按钮.
  showIndicators: true            #  是否显示指示器.
  autoLoop: true                  #  是否自动轮播.
  duration: 10                    #  切换延迟时间. 
  intervalTime: 10                #  自动切换下一张的间隔时间.


# 首页签名
dream:
  enable: true
  showTitle: true
  title: 钦念の梦想
  text: 一间瓦房、一亩良田、一亿存款

# 首页音乐
music:
  enable: true
  showTitle: true
  title: 钦念の音乐
  fixed: false             # 开启吸底模式
  autoplay: false          # 是否自动播放
  theme: '#42b983'
  loop: 'all'              # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'list'            # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto'          # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7              # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: false        # 列表默认折叠
  listMaxHeight:           #列表最大高度

# 首页视频
video:
  enable: false
  showTitle: true
  title: 钦念の视频
  url:                  # 必填
  pic:
  thumbnails:
  height:               # 如：400
  autoplay: false       # 是否自动播放
  theme: '#42b983'
  loop: false           # 是否循环播放
  preload: 'auto'       # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7

# 推荐文章
recommend:
  showTitle: true

# 配置网站favicon和网站LOGO
favicon: /favicon.png
logo: /medias/logo.png

# 首页 banner 中的第二个按钮的配置，包括按钮的显示名称、font awesome 图标和按钮的超链接.
indexbtn:
  enable: true
  name: Github
  icon: fa-github-alt
  url: https://github.com/qinnian/

# 首页 banner 中的第二行个人信息配置，留空即不启用
socialLink:
  github: https://github.com/qinnian/
  email: liuxinwei1999@yeah.net
  facebook: 
  twitter: 
  qq: 
  weibo: https://weibo.com/Qinnianyedu5211314?is_all=1
  zhihu: https://www.zhihu.com/people/qin.nian/activities

# 是否激活文章 TOC 功能，并配置TOC支持选中哪些标题类型，这是全局配置。
# 可以在某篇文章的 Front-matter 中再加上`toc: false`，使该篇文章关闭TOC目录功能
toc:
  enable: true
  heading: h2, h3, h4
  showToggleBtn: true    # 是否显示切换TOC目录展开收缩的按钮

# 代码是否折行
code:
  break: true

# 是否激活文章末尾的打赏功能，默认激活
reward:
  enable: true
  title: 给钦念的早餐加个鸡蛋
  wechat: /medias/reward/wechat.png
  alipay: /medias/reward/alipay.jpg

# 是否激活复制文章时追加博客和作者的版权信息.
copyright:
  enable: true
  minCharNumber: 50 # 至少复制多少个字符就追加版权信息.
  description: 本文章著作权归作者钦念所有，任何形式的转载都请注明出处，联系邮箱：liuxinwei1999@yeah.net

# 是否激活mathjax数学公式，这是全局配置，但文章仍然不会都开启mathjax渲染，
# 考虑到mathjax加载比较耗时，你还需要在需要渲染的文章的Front-matter中再加上`mathjax: true`才行.
mathjax:
  enable: true
  cdn: https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# 文章字数统计、阅读时长、总字数统计
# 激活前请确认你已经安装了 hexo-wordcount 插件，安装命令: `npm i --save hexo-wordcount`
wordCount:
  enable: true
  postWordCount: true
  min2read: true
  totalCount: true

# 是否激活点击页面的'爱心'效果，默认激活.
clicklove:
  enable: true

# 在”关于”页面中配置个人信息，包括头像、职业和个人介绍.
profile:
  avatar: /medias/avatar.jpg
  career: 石家庄铁道大学 | 数字媒体技术
  introduction: 慎思明辨 知行合一 

# 在“关于”页面配置"我的项目"信息
myProjects:
  enable: false
  data:
    project1:
      icon: fa-meetup
      iconBackground: 'linear-gradient(to bottom right, #66BB6A 0%, #81C784 100%)'
      url: http://github.com/qinnian
      desc: 描述
    project1:
        icon: fa-database
        iconBackground: 'linear-gradient(to bottom right, #F06292 0%, #EF5350 100%)'
        url: https://github.com/qinnian
        desc: 描述

# 在“关于”页面配置"我的技能"信息
mySkills:
  enable: false
  data:
    JavaScript:
      background: 'linear-gradient(to right, #9900FF 0%, #CC66FF 100%)'
      percent: 40%
    HTML5:
      background: 'linear-gradient(to right, #2196F3 0%, #42A5F5 100%)'
      percent: 40%
    CSS:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 40%


# 在“关于”页面配置"我的相册"图片，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myGallery:
  enable: true
  data:
    - /medias/featureimages/0.jpg
    - /medias/featureimages/1.jpg
    - /medias/featureimages/2.jpg

# 设置在归档页面中是否显示'文章日历'控件
postCalendar: true

# Gitalk 评论模块的配置，默认为不激活
gitalk:
  enable: true
  owner: qinnian             #  GitHub repository 所有者，可以是个人或者组织
  repo: qinnian.github.io    #  GitHub repository.
  oauth: 
    clientId: XXXXXXXXX
    clientSecret: XXXXXXXXXXX
  admin: qinnian   

# Gitment 评论模块的配置，默认为不激活
gitment:
  enable: false
  owner:
  repo:
  oauth:
    clientId:
    clientSecret:

# Disqus评论模块的配置，默认为不激活
disqus:
  enable: false
  shortname:

# Livere 来必力评论模块的配置，默认为不激活
livere:
  enable: false
  uid:

# Valine 评论模块的配置，默认为不激活，如要使用，就请激活该配置项，并设置 appId 和 appKey.
valine:
  enable: false
  appId:
  appKey:
  notify: false
  verify: false
  visitor: true
  avatar: 'mm' # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  pageSize: 10
  placeholder: 'just go go' # Comment Box placeholder

# 配置是否在 header 中显示 fork me on github 的图标，默认为true，你可以修改为你的仓库地址.
githubLink:
  enable: true
  url: https://github.com/qinnian/
  title: Fork Me

# 阅读文章的密码验证功能，如要使用此功能请激活该配置项，并在对应文章的Front-matter中写上'password'的键和加密后的密文即可.
# 请注意：为了保证密码原文不会被泄露到网页中，文章的密码必须是通过'SHA256'加密的，这样就不会被破解.
verifyPassword:
  enable: true                                # 密码已经激活
  promptMessage: 请输入访问本文章的密码
  errorMessage: 密码错误，将返回主页！

# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次

# 添加 Google Analytics 配置
googleAnalytics:
  enable: false
  id:

# 使用到的前端库，可按需替换成对应的CDN地址，如果下面未指定具体的版本号，使用最新的版本即可.
libs:
  css:
    valine: /libs/valine/Valine.min.js # 1.3.10  
    fontAwesome: /libs/awesome/css/font-awesome.min.css # V4.7.0
    materialize: /libs/materialize/materialize.min.css # 1.0.0
    aos: /libs/aos/aos.css
    animate: /libs/animate/animate.min.css # V3.5.1
    lightgallery: /libs/lightGallery/css/lightgallery.min.css # V1.6.11
    aplayer: /libs/aplayer/APlayer.min.css
    dplayer: /libs/dplayer/DPlayer.min.css
    gitalk: /libs/gitalk/gitalk.css
    jqcloud: /libs/jqcloud/jqcloud.css
    tocbot: /libs/tocbot/tocbot.css
  js:
    jquery: /libs/jquery/jquery-2.2.0.min.js
    materialize: /libs/materialize/materialize.min.js # 1.0.0
    masonry: /libs/masonry/masonry.pkgd.min.js # v4.0.0
    aos: /libs/aos/aos.js
    scrollProgress: /libs/scrollprogress/scrollProgress.min.js
    lightgallery: /libs/lightGallery/js/lightgallery-all.min.js # V1.6.11
    clicklove: /libs/others/clicklove.js
    busuanzi: /libs/others/busuanzi.pure.mini.js
    aplayer: /libs/aplayer/APlayer.min.js
    dplayer: /libs/dplayer/DPlayer.min.js
    crypto: /libs/cryptojs/crypto-js.min.js
    echarts: /libs/echarts/echarts.min.js
    gitalk: /libs/gitalk/gitalk.min.js
    jqcloud: /libs/jqcloud/jqcloud-1.0.4.min.js
    tocbot: /libs/tocbot/tocbot.min.js

# 无文章特色图片时需要显示的文章特色图片.
featureImages: 
- /medias/featureimages/0.jpg
- /medias/featureimages/1.jpg
- /medias/featureimages/2.jpg
- /medias/featureimages/3.jpg
- /medias/featureimages/4.jpg
- /medias/featureimages/5.jpg
- /medias/featureimages/6.jpg
- /medias/featureimages/7.jpg
- /medias/featureimages/8.jpg
- /medias/featureimages/9.jpg
- /medias/featureimages/10.jpg
- /medias/featureimages/11.jpg
- /medias/featureimages/12.jpg
- /medias/featureimages/13.jpg
- /medias/featureimages/14.jpg
- /medias/featureimages/15.jpg
- /medias/featureimages/16.jpg
- /medias/featureimages/17.jpg
- /medias/featureimages/18.jpg
- /medias/featureimages/19.jpg
- /medias/featureimages/20.jpg
- /medias/featureimages/21.jpg
- /medias/featureimages/22.jpg
- /medias/featureimages/23.jpg

  # default configs that the default policy for every articles/posts
  # default 配置文章的默认转载规则

  # you can define reprint policy for a single article in the front-matter of the specific md file using this key: reprintPolicy
  # 您可以使用在文章md文件的 front-matter 中指定 reprintPolicy 来给单个文章配置转载规则

  # 可用的转载规则有（available reprint policies are）：
  # 这些转载规则的意义请参考(you can refer to this link FMI)：https://creativecommons.org/choose/?lang=zh
  # cc_by（知识共享署名 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_nd（知识共享署名-禁止演绎 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_sa（知识共享署名-相同方式共享 4.0 国际许可协议 Creative Commons Attribution-ShareAlike 4.0 International License）
  # cc_by_nc（知识共享署名-非商业性使用 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_nc_nd（知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议 Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License）
  # cc_by_nc_sa（知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议 Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License）

  # cc0（CC0 1.0 通用 (CC0 1.0) 公共领域贡献 CC0 1.0 Universal (CC0 1.0) Public Domain Dedication） https://creativecommons.org/publicdomain/zero/1.0/deed.zh

  # noreprint（不允许转载 not allowed to reprint）
  # pay（付费转载 pay for reprinting）
reprint:
  enable: true               #  是否启用“转载规则限定模块”
  default: cc_by